apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: f1-agent

resources:
  - ../namespace.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: f1-penalty-agent
  app.kubernetes.io/managed-by: kustomize
